## zorn.kv
#:import colours web_safe_subset_rgb

## Changes needed for this to work with Magic Palette...
## -- increase number of columns to 7
## - import statement should point to magic_palette_fractional.py
## - Spinner values should point to ColourLookUp in the above file
## - dynamic_colour for each chip will default to Titanium White
##   in magic_palette_fractional.ColourLookUp
<ZornGridLayout>:
	rows: 6
	cols: 7
	
	##################### ROW 1 ##################
	BoxLayout: ## COLUMN 1
		orientation: 'vertical'
		size_hint: None, None
		width: 150
		height: 150
		NewButton:
			id: new_button
			text: "New"
			size_hint: None, None
			width: 150
			height: 50
			on_release: self.create_new()
		LoadButton:
			id: load_button
			text: "Load"
			size_hint: None, None
			width: 150
			height: 50
			on_release: self.load_palette()
		SaveButton:
			id: save_button
			text: "Save"
			size_hint: None, None
			width: 150
			height: 50
			on_release: self.save_palette()

	Label: ## empty square COLUMN 2
		text: "empty"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		
	Colour01Spinner: ## COLUMN 3
		id: colour_01_spinner
		text: "Colour 1"
		values: colours.WebColours
		size_hint: None, None
		size: 150, 150
		pos_hint: {'x': 0, 'top': 1}

		on_text:
			self.set_spinner_chip(self.text, colour_01)
			root.calculate_colours()

	Label: ## empty square COLUMN 4
		text: "empty"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## empty square COLUMN 5
		text: "empty"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## empty square COLUMN 6
		text: "empty"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Colour02Spinner: ## COLUMN 7
		id: colour_02_spinner
		text: "Colour 2"
		values: colours.WebColours
		size_hint: None, None
		size: 150, 150
		pos_hint: {'right': 1, 'top': 1}

		on_text:
			self.set_spinner_chip(self.text, colour_02)
			root.calculate_colours()
	
	##################### ROW 2 ##################
	Label: ## empty square COLUMN 1
		text: ""
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## empty square ## COLUMN 2
		text: ""
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## COLUMN 3
		id: colour_01
		text: "C1"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_01
		text: "chip 01"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 5
		id: chip_02
		text: "chip 02"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_03
		text: "chip 03"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: colour_02
		text: "C2"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	##################### ROW 3 ##################
	Tint01Spinner:
		id: tint_01_spinner
		text: "Tint 1"
		values: reversed(colours.WebColours)
		size_hint: None, None
		size: 150, 150
		pos_hint: {'left': 1, 'top': 1}

		on_text:
			self.set_spinner_chip(self.text, tint_01)
			root.calculate_colours()

	Label: ## COLUMN 2
		id: tint_01
		text: "T1"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 3
		id: chip_04
		text: "chip 04"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_05
		text: "chip 05"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 5
		id: chip_06
		text: "chip 06"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_07
		text: "chip 07"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: chip_08
		text: "chip 08"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	##################### ROW 4 ##################
	Label: ## COLUMN 1
		text: ""
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## COLUMN 2
		id: chip_09
		text: "chip 09"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 3
		id: chip_10
		text: "chip 10"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_11
		text: "chip 11"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 5
		id: chip_12
		text: "chip 12"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_13
		text: "chip 13"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: chip_14
		text: "chip 14"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	##################### ROW 5 ##################
	Label: ## COLUMN 1
		text: ""
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## COLUMN 2
		id: chip_15
		text: "chip 15"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 3
		id: chip_16
		text: "chip 16"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_17
		text: "chip 17"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_18
		text: "chip 18"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_19
		text: "chip 19"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: chip_20
		text: "chip 20"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	##################### ROW 6 ##################
	Label: ## COLUMN 1
		text: ""
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150

	Label: ## COLUMN 2
		id: chip_21
		text: "chip 21"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 3
		id: chip_22
		text: "chip 22"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_23
		text: "chip 23"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 5
		id: chip_24
		text: "chip 24"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_25
		text: "chip 25"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: chip_26
		text: "chip 26"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	##################### ROW 7 ##################
	Tint02Spinner: ## COLUMN 1
		id: side_colour_02
		text: "Tint 2"
		values: reversed(colours.WebColours)
		size_hint: None, None
		size: 150, 150
		pos_hint: {'left': 1, 'top': 1}

		on_text:
			self.set_spinner_chip(self.text, tint_02)
			root.calculate_colours()

	Label: ## COLUMN 2
		id: tint_02
		text: "T2"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 3
		id: chip_27
		text: "chip 27"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 4
		id: chip_28
		text: "chip 28"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 5
		id: chip_29
		text: "chip 29"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 6
		id: chip_30
		text: "chip 30"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size

	Label: ## COLUMN 7
		id: chip_31
		text: "chip 31"
		text_size: self.size
		size_hint: None, None
		width: 150
		height: 150
		dynamic_colour: (1, 1, 1, 1)

		canvas.before:
			Color:
				rgba: self.dynamic_colour
			Rectangle:
				pos: self.pos
				size: self.size


